# Generated by Django 5.2.17 on 2026-09-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, help_text='Static path or remote URL', max_length=300)),
                ('intro', models.TextField(blank=True)),
                ('lead', models.TextField(blank=True)),
                ('services', models.JSONField(blank=True, default=list)),
                ('paragraphs', models.JSONField(blank=True, default=list)),
                ('outro', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nutrikator', max_length=120)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('tagline', models.TextField(blank=True)),
                ('pib', models.CharField(blank=True, max_length=32)),
                ('maticni_broj', models.CharField(blank=True, max_length=32)),
                ('email_info', models.EmailField(blank=True, max_length=254)),
                ('email_privacy', models.EmailField(blank=True, max_length=254)),
                ('phone_sales', models.CharField(blank=True, max_length=64)),
                ('phone_office', models.CharField(blank=True, max_length=64)),
                ('founder_name', models.CharField(blank=True, max_length=120)),
                ('founder_title', models.CharField(blank=True, max_length=200)),
                ('address_footer', models.TextField(blank=True)),
                ('method', models.JSONField(blank=True, default=dict)),
                ('funding', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.JSONField(default=list, help_text='List of paragraphs')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body_md', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=40)),
                ('options', models.JSONField(blank=True, default=list)),
                ('hint', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('multiple', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(default='RSD', max_length=8)),
                ('featured', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('cta', models.CharField(blank=True, max_length=120)),
                ('features', models.JSONField(default=list)),
                ('sample_report', models.URLField(blank=True)),
                ('sample_label', models.URLField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(default='home', unique=True)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
